version: "3.3"

services:
  firefly-app:
    image: fireflyiii/core:version-6.1.18
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.entrypoints=websecure"
      - "traefik.http.routers.firefly.rule=Host(`firefly.${DOMAIN}`)"
      - "traefik.http.routers.firefly.tls.certresolver=letsencrypt"
      - "traefik.http.routers.firefly.tls=true"
    hostname: app
    container_name: firefly_iii_core
    restart: always
    env_file:
      - .env
      - .secrets
    networks:
      - private_network
    volumes:
      - /mnt/data/firefly/firefly_iii_upload:/var/www/html/storage/upload
    depends_on:
      - db
  db:
    image: mariadb:11.4.2
    hostname: db
    container_name: firefly_iii_db
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    restart: always
    env_file:
      - .db.env
      - .secrets
    networks:
      - private_network
    volumes:
      - /mnt/data/firefly/firefly_iii_db:/var/lib/mysql
  importer:
    image: fireflyiii/data-importer:version-1.4.5
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    env_file:
      - .importer.env
      - .secrets
    volumes:
      - /mnt/data/firefly/firefly_iii_importer:/var/www/html/storage/upload
      - /documents:/import
    networks:
      - private_network
    depends_on:
      - firefly-app
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long.
    #
    image: alpine:3.21.2
    restart: always
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/GLekbidm9OfJdb0UrddF3vwjs7g66BqL\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - private_network

