#https://github.com/immich-app/immich/tree/main/docker
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
      - .secrets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
      - "traefik.http.routers.immich.tls=true"
      - "docker-volume-backup.stop-during-backup=true"
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - private_network

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /immich-cache:/cache
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    env_file:
      - .env
      - .secrets
    restart: always
    networks:
      - private_network

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    networks:
      - private_network

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
      - .secrets
    environment:
      # This is not needed since we get the passoword from infisical.
      #POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    volumes:
      - /mnt/data/immich/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - private_network

  backup-db-immich:
    container_name: backup-db-immich
    image: prodrigestivill/postgres-backup-local
    env_file:
      - .env
      - .secrets
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "30 0 * * *"
      BACKUP_DIR: /db_dumps
    volumes:
      - /backups/server-2/immich-postgres/db_dumps:/db_dumps
    depends_on:
      - database
    networks:
      - private_network

