# metabase with postgre database
version: '3'
services:
  metabase:
    container_name: metabase-app
    image: bobblybook/metabase:v0.52.6
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "traefik.enable=true"
      - "traefik.http.routers.metabase.entrypoints=websecure"
      - "traefik.http.routers.metabase.rule=Host(`metabase.${DOMAIN}`)"
      - "traefik.http.routers.metabase.tls.certresolver=letsencrypt"
      - "traefik.http.routers.metabase.tls=true"
      - "traefik.http.services.metabase.loadbalancer.server.port=3000"
    env_file: 
     - .secrets
    volumes:
      - /mnt/data/metabase/data:/metabase
      - /dev/urandom:/dev/random:ro
    networks:
      - private_network
    environment:
      MB_DB_TYPE: postgres
      MB_DB_PORT: 5432
      MB_DB_HOST: postgres
      MB_DB_DBNAME: metabase
    depends_on:
      - 'postgres'

  adminer:
    image: adminer:4.8.1
    container_name: metabase-adminer
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    restart: always
    networks:
      - private_network
    depends_on:
      - 'postgres'

  postgres:
    image: postgres:16.3
    container_name: metabase-postgres
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    hostname: postgres
    env_file: 
     - .secrets
    environment:
      POSTGRES_DB: metabase
    networks:
      - private_network
    volumes:
      - /mnt/data/metabase/postgres/data:/var/lib/postgresql/data
