version: "3"
include:
  - ./traefik/docker-compose.yaml
  - ./docker-backup/docker-compose.yaml
  - ./dashy/docker-compose.yaml
  - ./uptime/docker-compose.yaml
networks:
  private_network:
    name: private_network
    driver: bridge 
    ipam:
      config:
        - subnet: 172.28.1.0/24
