#https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.sqlite.yml
version: "3.4"
services:
  broker:
    container_name: paperless-broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    networks:
      - private_network
    volumes:
      - /mnt/data/paperless/redisdata:/data

  webserver:
    container_name: paperless-web-server
    image: ghcr.io/paperless-ngx/paperless-ngx:2.2.0
    restart: unless-stopped
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    networks:
      - private_network
    depends_on:
      - broker
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/data/paperless/data:/usr/src/paperless/data
      - /documents/media:/usr/src/paperless/media
      - /mnt/data/paperless/export:/usr/src/paperless/export
      - /documents/consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://172.30.1.28:6379