---
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC2
    container_name: mealie
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.rule=Host(`mealie.${DOMAIN}`)"
      - "traefik.http.routers.mealie.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mealie.tls=true"
    deploy:
      resources:
        limits:
          memory: 1000M 
    volumes:
      - /mnt/data/mealie/mealie-data:/app/data/
    networks:
      - private_network
    environment:
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.020881.xyz
    restart: always