version: '3.8'

services:
  zigbee2mqtt:
    image:  koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.entrypoints=websecure"
      - "traefik.http.routers.uptime.rule=Host(`z2m.${DOMAIN}`)"
      - "traefik.http.routers.uptime.tls.certresolver=letsencrypt"
      - "traefik.http.routers.uptime.tls=true"
      - "traefik.http.services.z2m.loadbalancer.server.port=8080"
    networks:
      - private_network
    environment:
    - TZ=Europe/Amsterdam
    volumes:
      - /mnt/data/zigbee2mqtt/data:/app/data
    restart: always
