version: "2.4"
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.entrypoints=websecure"
      - "traefik.http.routers.freshrss.rule=Host(`rss.${DOMAIN}`)"
      - "traefik.http.routers.freshrss.tls.certresolver=letsencrypt"
      - "traefik.http.routers.freshrss.tls=true"
    restart: always
    networks:
      - private_network
    hostname: freshrss
    env_file: 
    - .env
    - .secrets
    logging:
      options:
        max-size: 10m
    volumes:
      - /mnt/data/freshrss/data:/var/www/FreshRSS/data
      - /mnt/data/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Amsterdam
      CRON_MIN: '3,33'
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
