version: "3"

services:
  adguard:
    container_name: adguard
    hostname: adguard
    labels:
      - "docker-volume-backup.stop-during-backup=true"
    image: adguard/adguardhome:v0.107.55
    restart: unless-stopped
    networks:
      - private_network
    volumes:
      - /mnt/data/adguard-home/work:/opt/adguardhome/work
      - /mnt/data/adguard-home/conf:/opt/adguardhome/conf
