# This is a basic workflow to help you get started with Actions
name: Destroy

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  workflow_dispatch:

env:
  tf_version: "1.8.1"
  tg_version: "0.67.0"
  infra: infra
  containers_host: containers-host
  TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
  TF_VAR_aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
  REPOSITORY: ${{ github.repository }}
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  destroy-containers-host:
    runs-on: ubuntu-latest
    environment: "prod"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc
          role-session-name: GitHub_to_AWS_OIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Destroy Host
        uses: gruntwork-io/terragrunt-action@v2
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          INFISICAL_PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.containers_host }}
          tg_command: "destroy"

  destroy-infra:
    runs-on: ubuntu-latest
    needs: [destroy-containers-host]
    environment: "prod"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc
          role-session-name: GitHub_to_AWS_OIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        id: deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.infra }}
          tg_command: "destroy"
