version: "3.8"
services:
  baikal:
    image: ckulka/baikal:0.10.1-nginx
    container_name: baikal
    labels:
      - "docker-volume-backup.stop-during-backup=true"
      - "traefik.enable=true"
      - "traefik.http.routers.baikal.entrypoints=websecure"
      - "traefik.http.routers.baikal.rule=Host(`baikal.${DOMAIN}`)"
      - "traefik.http.routers.baikal.tls.certresolver=letsencrypt"
      - "traefik.http.routers.baikal.tls=true"
    restart: always
    networks:
      - private_network
    volumes:
      - /mnt/data/baikal/config:/var/www/baikal/config
      - /mnt/data/baikal/Specific:/var/www/baikal/Specific
